/**
 * DTOs mirroring BACKEND_CONTRACT.md §5 and the Flutter models.
 * Wire format is snake_case; we map to camelCase at the boundary (see mappers).
 */

export type AutonomyLevel = "auto" | "ask" | "never";

export const ACTION_TYPES = [
  "reply_email",
  "send_email",
  "draft_email",
  "block_sender",
  "mark_read",
  "archive_email",
  "create_event",
  "delete_event",
  "schedule_reminder",
] as const;
export type ActionType = (typeof ACTION_TYPES)[number];

export const EMAIL_RULE_ACTIONS = [
  "block",
  "mark_read",
  "archive",
  "notify_never",
] as const;
export type EmailRuleAction = (typeof EMAIL_RULE_ACTIONS)[number];

export type MessageRole = "user" | "assistant" | "tool";

export interface ActionData {
  label: string;
  to: string;
  subject: string;
  bodyPreview: string;
}

export interface ConversationHistory {
  conversationId: string;
  messages: { role: MessageRole; content: string; createdAt: string; isAction?: boolean; actionCancelled?: boolean; actionError?: string; actionData?: ActionData; failedAction?: PendingAction; suggestions?: SuggestedReply[] }[];
}

export interface User {
  id: string;
  email: string;
  displayName?: string | null;
  fcmToken?: string | null;
}

export interface AutonomySetting {
  actionType: ActionType;
  level: AutonomyLevel;
}

export interface NotificationPreferences {
  enabled: boolean;
  channelEmail: boolean;
  channelWhatsapp: boolean;
  notifyEmailAccountId: string | null;
  notifyWhatsappNumberId: string | null;
  eventNoticeMinutes: number;
}

export interface EmailRule {
  id: string;
  senderPattern: string;
  action: EmailRuleAction;
  notify: boolean;
  createdAt?: string | null;
}

export interface Reminder {
  id: string;
  message: string;
  fireAt: string; // ISO 8601
  fired: boolean;
  source?: string | null;
  metadata?: Record<string, unknown> | null;
}

export interface PendingAction {
  id: string;
  actionType: string;
  payload: Record<string, unknown>;
  status: "pending" | "approved" | "rejected" | "expired";
  createdAt?: string | null;
}

export interface EmailRef {
  id: string;
  threadId?: string | null;
  sender: string;
  subject: string;
  date: string;
  snippet: string;
  unread: boolean;
}

export interface EmailContent extends EmailRef {
  to: string;
  body: string;
}

export interface SuggestedReply {
  label: string;
  body: string;
  to: string;
  messageId: string;
  subject: string;
}

export interface ChatMessage {
  id?: string;
  role: MessageRole;
  content: string;
  createdAt: string;
  /** true while waiting for the assistant reply (typing indicator) */
  pending?: boolean;
  /** transient tool-progress label shown while streaming ("Reading your inbox…") */
  statusText?: string;
  /** rendered as a rich action card instead of a chat bubble */
  isAction?: boolean;
  /** data for the action card (label, to, subject, body preview) */
  actionData?: ActionData;
  /** true when user explicitly cancelled the pending action */
  actionCancelled?: boolean;
  /** non-empty string means the action failed; renders an error card */
  actionError?: string;
  /** stored so the error card's "Try again" can retry the same suggestion */
  failedSuggestion?: SuggestedReply;
  /** stored so the error card's "Try again" can re-show the confirm banner */
  failedAction?: PendingAction;
  /** emails referenced by this reply, rendered as expandable cards */
  references?: EmailRef[];
  /** suggested replies generated by the agent */
  suggestions?: SuggestedReply[];
}

export interface ChatResult {
  reply: string;
  conversationId: string;
  pendingAction?: PendingAction | null;
  references?: EmailRef[];
  suggestions?: SuggestedReply[];
  isAction?: boolean;
  actionData?: ActionData;
}

export interface ConversationPage {
  conversationId: string;
  messages: ConversationHistory["messages"];
  hasMore: boolean;
}

export interface ConversationSummary {
  conversationId: string;
  title: string;
  lastAt?: string | null;
  messageCount: number;
}

export interface AgentProfile {
  agentName: string;
  tone: string;
  doExamples: string;
  dontExamples: string;
  scenarios: string;
  setupCompleted: boolean;
}

export type WhatsAppStatus = "pending_verification" | "active" | "failed" | "revoked";

export interface WhatsAppNumber {
  id: string;
  phoneNumber: string;
  status: WhatsAppStatus;
  verifiedAt?: string | null;
  lastInboundAt?: string | null;
  createdAt?: string | null;
}

export interface WhatsAppNumbersInfo {
  numbers: WhatsAppNumber[];
  emailConnected: boolean;
  canAdd: boolean;
  maxNumbers: number;
}

export type TelegramLinkStatus = "not_linked" | "pending_link" | "active";

export interface TelegramStatus {
  status: TelegramLinkStatus;
  link?: string | null;
  linkedAt?: string | null;
  emailConnected: boolean;
}

export type MessengerLinkStatus = "not_linked" | "pending_link" | "active";

export interface MessengerStatus {
  status: MessengerLinkStatus;
  link?: string | null;
  linkedAt?: string | null;
  emailConnected: boolean;
}

/** Open a message in Gmail's web UI. */
export function gmailLink(ref: { id: string; threadId?: string | null }): string {
  return `https://mail.google.com/mail/u/0/#all/${ref.threadId || ref.id}`;
}

export interface AuthResult {
  accessToken: string;
  refreshToken?: string | null;
  user: User;
}

// ---- Email Automation -------------------------------------------------------

export interface EmailAccount {
  id: string;
  userId: string;
  email: string;
  displayName?: string | null;
  pictureUrl?: string | null;
  systemPrompt: string;
  isActive: boolean;
  lastFetchedAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface KnowledgeBase {
  id: string;
  ownerId?: string | null;
  name: string;
  description: string;
  isGlobal: boolean;
  documentCount: number;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface KnowledgeDocument {
  id: string;
  kbId: string;
  name: string;
  content: string;
  source: string;
  createdAt?: string | null;
}

export const mapEmailAccount = (j: any): EmailAccount => ({
  id: j.id,
  userId: j.user_id,
  email: j.email,
  displayName: j.display_name ?? null,
  pictureUrl: j.picture_url ?? null,
  systemPrompt: j.system_prompt ?? "",
  isActive: j.is_active ?? true,
  lastFetchedAt: j.last_fetched_at ?? null,
  createdAt: j.created_at ?? null,
  updatedAt: j.updated_at ?? null,
});

export const mapKnowledgeBase = (j: any): KnowledgeBase => ({
  id: j.id,
  ownerId: j.owner_id ?? null,
  name: j.name,
  description: j.description ?? "",
  isGlobal: j.is_global ?? false,
  documentCount: j.document_count ?? 0,
  createdAt: j.created_at ?? null,
  updatedAt: j.updated_at ?? null,
});

export const mapKnowledgeDocument = (j: any): KnowledgeDocument => ({
  id: j.id,
  kbId: j.kb_id,
  name: j.name,
  content: j.content,
  source: j.source ?? "",
  createdAt: j.created_at ?? null,
});

// ---- display helpers (parity with Flutter) --------------------------------

export function autonomyDisplayName(actionType: string): string {
  switch (actionType) {
    case "reply_email":      return "Reply to emails";
    case "send_email":       return "Send new emails";
    case "draft_email":      return "Save email drafts";
    case "block_sender":     return "Block senders";
    case "mark_read":        return "Mark as read";
    case "archive_email":    return "Archive emails";
    case "create_event":     return "Create calendar events";
    case "delete_event":     return "Delete calendar events";
    case "schedule_reminder": return "Schedule reminders";
    default:                 return actionType;
  }
}

export function emailRuleActionLabel(action: string): string {
  switch (action) {
    case "block":
      return "Block";
    case "mark_read":
      return "Mark read";
    case "archive":
      return "Archive";
    case "notify_never":
      return "Never notify";
    default:
      return action;
  }
}

const truncate = (v: unknown, max = 60): string => {
  const s = String(v ?? "");
  return s.length <= max ? s : `${s.slice(0, max)}…`;
};

/** Human summary of a pending action, mirroring Flutter PendingAction.summary. */
export function pendingActionSummary(a: PendingAction): string {
  const p = a.payload ?? {};
  switch (a.actionType) {
    case "reply_email":
      return `Reply to ${p.to ?? "an email"}: "${truncate(p.body)}"`;
    case "block_sender":
      return `Block ${p.sender_email ?? "a sender"}`;
    case "mark_read":
      return "Mark an email as read";
    case "archive_email":
      return "Archive an email";
    case "create_event":
      return `Create event "${p.summary ?? ""}" at ${p.start ?? ""}`;
    case "delete_event":
      return "Delete a calendar event";
    case "schedule_reminder":
      return `Schedule a reminder: "${truncate(p.message)}"`;
    default:
      return `Perform: ${a.actionType}`;
  }
}

// ---- helpers ---------------------------------------------------------------

/** Decode HTML entities that Gmail includes in snippets (e.g. &#39; → '). */
function decodeHtml(str: string): string {
  return str
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&nbsp;/g, " ");
}

// ---- wire mappers (snake_case JSON -> camelCase) --------------------------

/* eslint-disable @typescript-eslint/no-explicit-any */
export const mapUser = (j: any): User => ({
  id: j.id,
  email: j.email,
  displayName: j.display_name ?? null,
  fcmToken: j.fcm_token ?? null,
});

export const mapAutonomy = (j: any): AutonomySetting => ({
  actionType: j.action_type,
  level: (j.level ?? "ask") as AutonomyLevel,
});

export const mapEmailRule = (j: any): EmailRule => ({
  id: j.id,
  senderPattern: j.sender_pattern,
  action: j.action,
  notify: j.notify ?? false,
  createdAt: j.created_at ?? null,
});

export const mapReminder = (j: any): Reminder => ({
  id: j.id,
  message: j.message,
  fireAt: j.fire_at,
  fired: j.fired ?? false,
  source: j.source ?? null,
  metadata: j.metadata ?? null,
});

export const mapPendingAction = (j: any): PendingAction => ({
  id: j.id,
  actionType: j.action_type,
  payload: j.payload ?? {},
  status: j.status ?? "pending",
  createdAt: j.created_at ?? null,
});

export const mapEmailRef = (j: any): EmailRef => ({
  id: j.id,
  threadId: j.thread_id ?? null,
  sender: j.sender ?? "",
  subject: j.subject ?? "",
  date: j.date ?? "",
  snippet: decodeHtml(j.snippet ?? ""),
  unread: j.unread ?? false,
});

export const mapEmailContent = (j: any): EmailContent => ({
  ...mapEmailRef(j),
  to: j.to ?? "",
  body: j.body ?? "",
});
/* eslint-enable @typescript-eslint/no-explicit-any */
